# Generated by Django 3.2.5 on 2021-10-13 04:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_snum', models.CharField(blank=True, default='', max_length=200, verbose_name='文章编号')),
                ('article_title', models.CharField(blank=True, default='', max_length=200, verbose_name='文章标题')),
                ('book_page', models.IntegerField(blank=True, default=None, help_text='文章在书籍中的页码', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='书籍页码')),
                ('article_page', models.IntegerField(blank=True, default=None, help_text='文章的相对页码', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='文章页码')),
                ('article_review_status', models.CharField(choices=[('unassign', '未分配'), ('unaudit', '待审核'), ('success', '成功'), ('fail', '失败'), ('returned', '退回'), ('suspend', '挂起')], default='unassign', max_length=20, verbose_name='文章校对状态')),
                ('article_open_status', models.CharField(choices=[('open', '开放'), ('close', '隐藏')], default='close', max_length=20, verbose_name='文章状态')),
                ('article_genre', models.CharField(blank=True, default='', max_length=50, verbose_name='文章体裁')),
                ('article_dynasty', models.CharField(blank=True, default='', max_length=50, verbose_name='文章朝代')),
                ('writing_mode', models.CharField(blank=True, choices=[('h', '横排'), ('v', '竖排')], default='', help_text='文章印刷的排版方向', max_length=10, verbose_name='文章排版')),
                ('reading_mode', models.CharField(blank=True, choices=[('lr', '左到右'), ('rl', '右到左')], default='', help_text='文章阅读方向', max_length=10, verbose_name='阅读方向')),
                ('content_image', models.CharField(help_text='文章所在页原件图片路径或URL', max_length=400, verbose_name='文章扫描件')),
                ('content_text', models.TextField(help_text='文章所在页 OCR 识别后的文字内容', verbose_name='文章内容')),
                ('created_time', models.DateTimeField(auto_now=True, db_index=True, help_text='数据入库时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='数据更新时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='作者姓名')),
                ('dynasty', models.CharField(blank=True, default='', max_length=50, verbose_name='作者朝代')),
                ('writing_school', models.CharField(blank=True, default='', max_length=50, verbose_name='作者流派')),
                ('created_time', models.DateTimeField(auto_now=True, db_index=True, help_text='数据入库时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='数据更新时间', verbose_name='更新时间')),
                ('operator', models.ForeignKey(blank=True, default=None, help_text='数据操作人', null=True, on_delete=django.db.models.deletion.PROTECT, to='userprofile.userprofile', verbose_name='操作人')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
            },
        ),
        migrations.CreateModel(
            name='QAOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_id', models.CharField(db_index=True, default=None, max_length=200, null=True, verbose_name='质检工单编号')),
                ('bulk_id', models.CharField(db_index=True, default=None, max_length=200, null=True, verbose_name='质检工单批次号')),
                ('qa_type', models.CharField(choices=[('no_qa', '一键放通'), ('sample', '抽样质检')], default='', max_length=50, verbose_name='质检类型')),
                ('status', models.CharField(choices=[('unassign', '未分配'), ('unaudit', '待审核'), ('success', '成功'), ('fail', '失败'), ('returned', '退回'), ('suspend', '挂起')], default='unassign', max_length=50, verbose_name='质检状态')),
                ('remark', models.TextField(blank=True, default='', max_length=2000, verbose_name='质检备注')),
                ('created_time', models.DateTimeField(auto_now=True, db_index=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('operator', models.ForeignKey(blank=True, default=None, help_text='操作人', null=True, on_delete=django.db.models.deletion.PROTECT, to='userprofile.userprofile', verbose_name='操作人')),
                ('qa_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qaorder_user', to='userprofile.userprofile', verbose_name='质检人')),
            ],
            options={
                'verbose_name': '质检工单',
                'verbose_name_plural': '质检工单',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_snum', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='书籍编号')),
                ('book_name', models.CharField(db_index=True, max_length=200, verbose_name='书籍名称')),
                ('writing_mode', models.CharField(blank=True, choices=[('h', '横排'), ('v', '竖排')], default='', help_text='书籍印刷的排版方向', max_length=10, verbose_name='书籍排版')),
                ('reading_mode', models.CharField(blank=True, choices=[('lr', '左到右'), ('rl', '右到左')], default='', max_length=10, verbose_name='阅读方向')),
                ('book_genre', models.CharField(blank=True, default='', max_length=50, verbose_name='书籍体裁')),
                ('book_dynasty', models.CharField(blank=True, default='', help_text='书籍编纂朝代', max_length=50, verbose_name='书籍朝代')),
                ('book_open_status', models.CharField(choices=[('open', '开放'), ('close', '隐藏')], default='close', help_text='书籍是否开放给查询', max_length=20, verbose_name='书籍状态')),
                ('created_time', models.DateTimeField(auto_now=True, db_index=True, help_text='数据入库时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='数据更新时间', verbose_name='更新时间')),
                ('authors', models.ManyToManyField(to='findiff.Author')),
                ('operator', models.ForeignKey(blank=True, default=None, help_text='数据操作人', null=True, on_delete=django.db.models.deletion.PROTECT, to='userprofile.userprofile', verbose_name='操作人')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
            },
        ),
        migrations.CreateModel(
            name='AuditProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unassign', '未分配'), ('unaudit', '待审核'), ('success', '成功'), ('fail', '失败'), ('returned', '退回'), ('suspend', '挂起')], default='unassign', max_length=50, null=True, verbose_name='审核状态')),
                ('content_text', models.TextField(verbose_name='内容校对结果')),
                ('article_title', models.CharField(blank=True, default='', max_length=200, verbose_name='文章标题校对结果')),
                ('article_page', models.IntegerField(blank=True, default=None, help_text='文章的相对页码', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='文章页码校对结果')),
                ('writing_mode', models.CharField(blank=True, choices=[('h', '横排'), ('v', '竖排')], default='', help_text='文章印刷的排版方向', max_length=10, verbose_name='文章排版')),
                ('reading_mode', models.CharField(blank=True, choices=[('lr', '左到右'), ('rl', '右到左')], default='', help_text='文章阅读方向', max_length=10, verbose_name='阅读方向')),
                ('remark', models.TextField(blank=True, default='', max_length=2000, verbose_name='审核备注')),
                ('created_time', models.DateTimeField(auto_now=True, db_index=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('article_author', models.ForeignKey(blank=True, default=None, help_text='文章作者', null=True, on_delete=django.db.models.deletion.PROTECT, to='findiff.author')),
                ('audit_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditprofile_audit_user', to='userprofile.userprofile', verbose_name='审核人')),
                ('operator', models.ForeignKey(blank=True, default=None, help_text='操作人', null=True, on_delete=django.db.models.deletion.PROTECT, to='userprofile.userprofile', verbose_name='操作人')),
            ],
            options={
                'verbose_name': '校对工单结果',
                'verbose_name_plural': '校对工单结果',
            },
        ),
        migrations.CreateModel(
            name='AuditOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_id', models.CharField(db_index=True, max_length=200, verbose_name='校对工单编号')),
                ('order_status', models.CharField(choices=[('1100', '一审未分配'), ('1101', '一审待审核'), ('1102', '一审成功'), ('1103', '一审退回'), ('1104', '一审失败'), ('1105', '一审挂起'), ('1200', '二审未分配'), ('1201', '二审待审核'), ('1202', '二审成功'), ('1203', '二审退回'), ('1204', '二审失败'), ('1205', '二审挂起'), ('2100', '质检未分配'), ('2101', '质检待审核'), ('2102', '质检成功'), ('2103', '质检退回'), ('2104', '质检失败'), ('2105', '质检挂起')], default='1100', max_length=10, verbose_name='工单状态')),
                ('returned_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='打回次数')),
                ('returned_remark', models.TextField(blank=True, default='', max_length=2000, verbose_name='打回备注')),
                ('created_time', models.DateTimeField(auto_now=True, db_index=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='findiff.article', verbose_name='原内容信息')),
                ('first_audit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditorder_first', to='findiff.auditprofile', verbose_name='一审结果')),
                ('operator', models.ForeignKey(blank=True, default=None, help_text='操作人', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditorder_operator', to='userprofile.userprofile', verbose_name='操作人')),
                ('qa_audit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='findiff.qaorder', verbose_name='质检结果')),
                ('second_audit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditorder_second', to='findiff.auditprofile', verbose_name='二审结果')),
            ],
            options={
                'verbose_name': '校对工单',
                'verbose_name_plural': '校对工单',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, default=None, help_text='作者', null=True, on_delete=django.db.models.deletion.PROTECT, to='findiff.author'),
        ),
        migrations.AddField(
            model_name='article',
            name='book',
            field=models.ForeignKey(help_text='书籍', on_delete=django.db.models.deletion.PROTECT, to='findiff.book'),
        ),
        migrations.AddField(
            model_name='article',
            name='operator',
            field=models.ForeignKey(blank=True, default=None, help_text='数据操作人', null=True, on_delete=django.db.models.deletion.PROTECT, to='userprofile.userprofile', verbose_name='操作人'),
        ),
    ]
