# Generated by Django 3.2.5 on 2021-09-22 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='作者姓名')),
                ('dynasty', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='作者朝代')),
                ('writing_school', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='作者流派')),
                ('created_time', models.DateTimeField(auto_now=True, db_index=True, help_text='数据入库时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='数据更新时间', verbose_name='更新时间')),
                ('operator', models.ForeignKey(blank=True, default=None, help_text='数据操作人', on_delete=django.db.models.deletion.PROTECT, to='userprofile.userprofile', verbose_name='操作人')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_snum', models.CharField(blank=True, default=None, max_length=200, verbose_name='书籍编号')),
                ('book_name', models.CharField(db_index=True, max_length=200, verbose_name='书籍名称')),
                ('writing_mode', models.CharField(choices=[('h', '横排'), ('v', '竖排')], help_text='书籍印刷的排版方向', max_length=10, verbose_name='书籍排版')),
                ('reading_mode', models.CharField(choices=[('lr', '左到右'), ('rl', '右到左')], max_length=10, verbose_name='阅读方向')),
                ('book_genre', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='书籍体裁')),
                ('book_dynasty', models.CharField(blank=True, default=None, help_text='书籍编纂朝代', max_length=50, null=True, verbose_name='书籍朝代')),
                ('book_open_status', models.CharField(choices=[('open', '开放'), ('close', '隐藏')], default=True, help_text='书籍是否开放给查询', max_length=20, null=True, verbose_name='书籍状态')),
                ('created_time', models.DateTimeField(auto_now=True, db_index=True, help_text='数据入库时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='数据更新时间', verbose_name='更新时间')),
                ('authors', models.ManyToManyField(to='findiff.Author')),
                ('operator', models.ForeignKey(blank=True, default=None, help_text='数据操作人', on_delete=django.db.models.deletion.PROTECT, to='userprofile.userprofile', verbose_name='操作人')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_snum', models.CharField(blank=True, default=None, max_length=200, verbose_name='文章编号')),
                ('article_title', models.CharField(blank=True, default=None, max_length=200, verbose_name='文章标题')),
                ('book_page', models.IntegerField(blank=True, default=None, help_text='文章在书籍中的页码', null=True, verbose_name='书籍页码')),
                ('article_page', models.IntegerField(blank=True, default=None, help_text='文章的相对页码', null=True, verbose_name='文章页码')),
                ('article_review_status', models.CharField(choices=[('unassign', '未分配'), ('unaudit', '待审核'), ('success', '成功'), ('fail', '失败'), ('suspend', '挂起')], default='unssign', max_length=20, verbose_name='文章校对状态')),
                ('article_open_status', models.CharField(choices=[('open', '开放'), ('close', '隐藏')], default='close', max_length=20, verbose_name='文章状态')),
                ('article_genre', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='文章体裁')),
                ('article_dynasty', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='文章朝代')),
                ('content_image', models.CharField(help_text='文章所在页原件图片路径或URL', max_length=400, verbose_name='文章扫描件')),
                ('content_text', models.TextField(help_text='文章所在页 OCR 识别后的文字内容', verbose_name='文章内容')),
                ('created_time', models.DateTimeField(auto_now=True, db_index=True, help_text='数据入库时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='数据更新时间', verbose_name='更新时间')),
                ('author_id', models.ForeignKey(help_text='作者', on_delete=django.db.models.deletion.PROTECT, to='findiff.author')),
                ('book_id', models.ForeignKey(help_text='书籍', on_delete=django.db.models.deletion.PROTECT, to='findiff.book')),
                ('operator', models.ForeignKey(blank=True, default=None, help_text='数据操作人', on_delete=django.db.models.deletion.PROTECT, to='userprofile.userprofile', verbose_name='操作人')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
