# Generated by Django 3.2.5 on 2022-01-18 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now=True, db_index=True, help_text='数据入库时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='数据更新时间', verbose_name='更新时间')),
                ('nickname', models.CharField(blank=True, help_text='昵称支持最多30个字符', max_length=30, null=True, unique=True, verbose_name='昵称')),
                ('phone', models.CharField(blank=True, help_text='联系电话', max_length=30, verbose_name='联系电话')),
                ('operator', models.ForeignKey(blank=True, default=None, help_text='数据操作人', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='findiff_userprofile_operator', to='findiff.userprofile', verbose_name='操作人')),
                ('user', models.OneToOneField(help_text='DjangoAdmin用户', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='DjangoAdmin用户')),
            ],
            options={
                'verbose_name': '系统用户',
                'verbose_name_plural': '系统用户',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now=True, db_index=True, help_text='数据入库时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='数据更新时间', verbose_name='更新时间')),
                ('music_no', models.IntegerField(db_index=True, default=None, null=True, verbose_name='歌曲编号')),
                ('label', models.CharField(default='', max_length=100, verbose_name='候选词')),
                ('is_matched', models.IntegerField(choices=[(0, '不是'), (1, '是')], default=0, verbose_name='是否匹配')),
                ('operator', models.ForeignKey(blank=True, default=None, help_text='数据操作人', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='findiff_labels_operator', to='findiff.userprofile', verbose_name='操作人')),
            ],
            options={
                'verbose_name': '歌曲标注词',
                'verbose_name_plural': '歌曲标注词',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now=True, db_index=True, help_text='数据入库时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='数据更新时间', verbose_name='更新时间')),
                ('music_no', models.IntegerField(db_index=True, default=None, null=True, verbose_name='歌曲编号')),
                ('comment', models.TextField(blank=True, default='', verbose_name='评论内容')),
                ('likes', models.IntegerField(blank=True, default=0, verbose_name='点赞数')),
                ('operator', models.ForeignKey(blank=True, default=None, help_text='数据操作人', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='findiff_comments_operator', to='findiff.userprofile', verbose_name='操作人')),
            ],
            options={
                'verbose_name': '歌曲评论',
                'verbose_name_plural': '歌曲评论',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='AuditOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now=True, db_index=True, help_text='数据入库时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='数据更新时间', verbose_name='更新时间')),
                ('music_no', models.IntegerField(db_index=True, default=None, null=True, verbose_name='歌曲编号')),
                ('status', models.CharField(blank=True, choices=[('unassign', '未分配'), ('unaudit', '待校对'), ('success', '成功'), ('fail', '失败')], db_index=True, default='unassign', max_length=30, verbose_name='标注状态')),
                ('maker', models.ForeignKey(blank=True, default=None, help_text='标注人', null=True, on_delete=django.db.models.deletion.PROTECT, to='findiff.userprofile', verbose_name='标注人')),
                ('operator', models.ForeignKey(blank=True, default=None, help_text='数据操作人', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='findiff_auditorder_operator', to='findiff.userprofile', verbose_name='操作人')),
            ],
            options={
                'verbose_name': '校对工单',
                'verbose_name_plural': '校对工单',
                'ordering': ['-created_time'],
            },
        ),
    ]
