# Generated by Django 3.2.5 on 2022-01-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findiff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labels',
            name='is_matched',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否匹配'),
        ),
    ]
