# Generated by Django 3.2.5 on 2022-01-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findiff', '0002_alter_labels_is_matched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labels',
            name='is_matched',
            field=models.IntegerField(blank=True, choices=[(0, '否'), (1, '是')], default=None, null=True, verbose_name='是否匹配'),
        ),
    ]
