# Generated by Django 3.2.5 on 2021-10-16 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findiff', '0002_book_book_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='book',
            field=models.ForeignKey(blank=True, default=None, help_text='书籍', null=True, on_delete=django.db.models.deletion.PROTECT, to='findiff.book'),
        ),
    ]
