# Generated by Django 3.2.5 on 2021-12-07 10:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_userprofile_options'),
        ('findiff', '0003_alter_article_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='detail',
            field=models.TextField(blank=True, default='', max_length=3000, verbose_name='作者介绍'),
        ),
        migrations.AddField(
            model_name='book',
            name='detail',
            field=models.TextField(blank=True, default='', max_length=3000, verbose_name='书籍介绍(PDF)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_page',
            field=models.IntegerField(blank=True, default=None, help_text='文章的相对页码', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='文章页码(非PDF)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_review_status',
            field=models.CharField(choices=[('unassign', '未分配'), ('unaudit', '待审核'), ('success', '成功'), ('fail', '失败'), ('returned', '驳回'), ('suspend', '挂起')], default='unassign', max_length=20, verbose_name='文章校对状态'),
        ),
        migrations.AlterField(
            model_name='article',
            name='book_page',
            field=models.IntegerField(blank=True, default=None, help_text='文章在书籍中的页码', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='书籍页码(PDF)'),
        ),
        migrations.AlterField(
            model_name='auditorder',
            name='order_status',
            field=models.CharField(choices=[('1100', '一审未分配'), ('1101', '一审待审核'), ('1102', '一审成功'), ('1103', '一审驳回'), ('1104', '一审失败'), ('1105', '一审挂起'), ('1200', '二审未分配'), ('1201', '二审待审核'), ('1202', '二审成功'), ('1203', '二审驳回'), ('1204', '二审失败'), ('1205', '二审挂起'), ('2100', '质检未分配'), ('2101', '质检待审核'), ('2102', '质检成功'), ('2103', '质检驳回'), ('2104', '质检失败'), ('2105', '质检挂起')], default='1100', max_length=10, verbose_name='工单状态'),
        ),
        migrations.AlterField(
            model_name='auditorder',
            name='returned_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='驳回次数'),
        ),
        migrations.AlterField(
            model_name='auditorder',
            name='returned_remark',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='驳回备注'),
        ),
        migrations.AlterField(
            model_name='auditprofile',
            name='status',
            field=models.CharField(choices=[('unassign', '未分配'), ('unaudit', '待审核'), ('success', '成功'), ('fail', '失败'), ('returned', '驳回'), ('suspend', '挂起')], default='unassign', max_length=50, null=True, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='书籍名称(PDF)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_pages',
            field=models.IntegerField(blank=True, default=0, verbose_name='书籍页数(PDF)'),
        ),
        migrations.AlterField(
            model_name='qaorder',
            name='status',
            field=models.CharField(choices=[('unassign', '未分配'), ('unaudit', '待审核'), ('success', '成功'), ('fail', '失败'), ('returned', '驳回'), ('suspend', '挂起')], default='unassign', max_length=50, verbose_name='质检状态'),
        ),
        migrations.CreateModel(
            name='UserKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now=True, db_index=True, help_text='数据入库时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='数据更新时间', verbose_name='更新时间')),
                ('hor_count', models.IntegerField(default=0, verbose_name='横排校对工单数量')),
                ('ver_count', models.IntegerField(default=0, verbose_name='竖排校对工单数量')),
                ('shuffle_count', models.IntegerField(default=0, verbose_name='被重新分单数量(校对失误导致)')),
                ('operator', models.ForeignKey(blank=True, default=None, help_text='数据操作人', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='findiff_userkpi_operator', to='userprofile.userprofile', verbose_name='操作人')),
                ('user', models.ForeignKey(help_text='校对人', on_delete=django.db.models.deletion.PROTECT, to='userprofile.userprofile', verbose_name='校对人')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
