# Generated by Django 3.2.5 on 2022-01-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findiff', '0003_alter_labels_is_matched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorder',
            name='status',
            field=models.CharField(blank=True, choices=[('unassign', '未分配'), ('unaudit', '待标注'), ('success', '成功'), ('fail', '失败')], db_index=True, default='unassign', max_length=30, verbose_name='标注状态'),
        ),
    ]
