# Generated by Django 3.2.5 on 2021-12-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findiff', '0004_auto_20211207_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userkpi',
            options={'verbose_name': '绩效', 'verbose_name_plural': '绩效'},
        ),
        migrations.AddField(
            model_name='article',
            name='writing_mode_origin',
            field=models.CharField(blank=True, choices=[('h', '横排'), ('v', '竖排')], default='', help_text='文章印刷的排版方向', max_length=10, verbose_name='文章排版原始值'),
        ),
        migrations.AlterField(
            model_name='article',
            name='writing_mode',
            field=models.CharField(blank=True, choices=[('h', '横排'), ('v', '竖排')], default='', help_text='文章印刷的排版方向', max_length=10, verbose_name='文章排版校对值'),
        ),
    ]
