# Generated by Django 3.2.5 on 2022-01-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findiff', '0004_alter_auditorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorder',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='是否隐藏该工单'),
        ),
    ]
