# Generated by Django 3.2.5 on 2021-12-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findiff', '0006_auto_20211208_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userkpi',
            name='hor_count',
        ),
        migrations.RemoveField(
            model_name='userkpi',
            name='shuffle_count',
        ),
        migrations.RemoveField(
            model_name='userkpi',
            name='ver_count',
        ),
        migrations.AddField(
            model_name='userkpi',
            name='count',
            field=models.IntegerField(default=0, verbose_name='绩效统计次数'),
        ),
        migrations.AddField(
            model_name='userkpi',
            name='trigger_step',
            field=models.CharField(blank=True, choices=[('first_audit', '一审'), ('second_audit', '二审'), ('qa', '质检')], default=None, max_length=50, null=True, verbose_name='绩效统计所在流程'),
        ),
        migrations.AddField(
            model_name='userkpi',
            name='type',
            field=models.CharField(choices=[('content_hor', '内容横排'), ('content_ver', '内容竖排'), ('order_returned_shuffle', '校对驳回')], default='', max_length=50, verbose_name='绩效类型'),
        ),
    ]
