# Generated by Django 3.2.5 on 2022-01-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findiff', '0008_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_text',
            field=models.TextField(blank=True, default='', help_text='文章所在页 OCR 识别后的文字内容', verbose_name='文章内容'),
        ),
    ]
