# Generated by Django 3.2.5 on 2021-08-18 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(blank=True, db_index=True, default='', max_length=10, verbose_name='书籍ID')),
                ('book_name', models.CharField(help_text='书名', max_length=200, verbose_name='书名')),
                ('writing_mode', models.CharField(choices=[('v', '横排'), ('h', '竖排')], db_index=True, help_text='排版方向', max_length=2, verbose_name='书籍排版')),
                ('content_image', models.CharField(help_text='每页原始的扫描图片', max_length=400, verbose_name='每页扫描件')),
                ('content_text', models.TextField(help_text='OCR 识别之后的文字内容', verbose_name='每页文字')),
                ('content_text_name', models.CharField(help_text='每页原始文件上传前的文件名', max_length=200, verbose_name='每页文件名')),
                ('content_image_name', models.CharField(help_text='扫描件上传前的文件名', max_length=200, verbose_name='每页扫描件名')),
            ],
            options={
                'verbose_name': '原始校对数据',
                'verbose_name_plural': '原始校对数据',
            },
        ),
        migrations.CreateModel(
            name='AuditOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, db_index=True, default='', help_text='订单号', max_length=40, verbose_name='订单号')),
                ('first_audit_time', models.DateTimeField(blank=True, db_index=True, help_text='初审时间', null=True, verbose_name='初审时间')),
                ('first_audit_result', models.TextField(blank=True, default='', help_text='初审提交内容', verbose_name='初审提交内容')),
                ('first_order_status', models.CharField(blank=True, choices=[('unassign', '未分配'), ('unaudit', '待审核'), ('success', '成功'), ('fail', '失败'), ('suspend', '挂起')], db_index=True, default='unassign', help_text='初审状态', max_length=30, verbose_name='初审状态')),
                ('second_audit_time', models.DateTimeField(blank=True, db_index=True, help_text='复审时间', null=True, verbose_name='复审时间')),
                ('second_audit_result', models.TextField(blank=True, default='', help_text='复审提交内容', verbose_name='复审提交内容')),
                ('second_order_status', models.CharField(blank=True, choices=[('unassign', '未分配'), ('unaudit', '待审核'), ('success', '成功'), ('fail', '失败'), ('suspend', '挂起')], db_index=True, default='unassign', help_text='复审状态', max_length=30, verbose_name='复审状态')),
                ('created_time', models.DateTimeField(auto_now=True, db_index=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('first_audit_user', models.ForeignKey(blank=True, default=None, help_text='初审人', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditorder_first_audit_user_set', to='userprofile.userprofile', verbose_name='初审人')),
                ('operator', models.ForeignKey(blank=True, default=None, help_text='操作人', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditorder_operator_set', to='userprofile.userprofile', verbose_name='操作人')),
                ('raw_data', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='review.rawdata', verbose_name='文件原始数据')),
                ('second_audit_user', models.ForeignKey(blank=True, default=None, help_text='复审人', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditorder_second_audit_user_set', to='userprofile.userprofile', verbose_name='复审人')),
            ],
            options={
                'verbose_name': '校对订单',
                'verbose_name_plural': '校对订单',
            },
        ),
    ]
