# Generated by Django 3.2.5 on 2021-08-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='writing_mode',
            field=models.CharField(choices=[('h', '横排'), ('v', '竖排')], db_index=True, help_text='排版方向', max_length=2, verbose_name='书籍排版'),
        ),
    ]
