# Generated by Django 3.2.5 on 2021-09-11 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FgUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, help_text='昵称支持最多30个字符', max_length=30, null=True, unique=True, verbose_name='昵称')),
                ('phone', models.CharField(blank=True, help_text='联系电话', max_length=30, verbose_name='联系电话')),
                ('join_time', models.DateTimeField(auto_now_add=True, help_text='注册时间', verbose_name='注册时间')),
                ('operate_time', models.DateTimeField(auto_now=True, help_text='操作时间', verbose_name='操作时间')),
                ('operator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='userprofile.userprofile', verbose_name='操作人')),
                ('user', models.OneToOneField(help_text='前台用户', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='前台用户')),
            ],
            options={
                'verbose_name': '前台用户',
                'verbose_name_plural': '前台用户',
                'ordering': ['-join_time'],
            },
        ),
    ]
