# Generated by Django 3.2.5 on 2021-10-13 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, help_text='昵称支持最多30个字符', max_length=30, null=True, unique=True, verbose_name='昵称')),
                ('phone', models.CharField(blank=True, help_text='联系电话', max_length=30, verbose_name='联系电话')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('operator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='userprofile.userprofile', verbose_name='操作人')),
                ('user', models.OneToOneField(help_text='DjangoAdmin用户', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='DjangoAdmin用户')),
            ],
            options={
                'verbose_name': '系统用户',
                'verbose_name_plural': '系统用户',
                'ordering': ['-create_time'],
                'permissions': [('list_audit_order', '校对工单列表'), ('scan_audit_order', '校对工单详情'), ('apply_audit_order', '校对领单'), ('submit_audit_order', '提交校对工单'), ('returned_audit_order', '打回校对工单'), ('create_audit_order', '创建校对工单'), ('modify_audit_order', '修改校对工单'), ('delete_audit_order', '删除校对工单'), ('list_qa_order', '查看质检工单'), ('apply_qa_order', '质检领单'), ('submit_qa_order', '提交质检工单'), ('returned_qa_order', '质检打回'), ('create_qa_order', '创建质检工单'), ('modify_qa_order', '修改质检工单'), ('delete_qa_order', '删除质检工单'), ('check_user_list', '查看用户列表'), ('assign_role_action', '分配用户角色'), ('check_user_group', '查看角色'), ('add_user_group', '增加角色'), ('edit_user_group', '编辑角色'), ('delete_user_group', '删除角色')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='FgUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, help_text='昵称支持最多30个字符', max_length=30, null=True, unique=True, verbose_name='昵称')),
                ('phone', models.CharField(blank=True, help_text='联系电话', max_length=30, verbose_name='联系电话')),
                ('join_time', models.DateTimeField(auto_now_add=True, help_text='注册时间', verbose_name='注册时间')),
                ('operate_time', models.DateTimeField(auto_now=True, help_text='操作时间', verbose_name='操作时间')),
                ('operator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='userprofile.userprofile', verbose_name='操作人')),
                ('user', models.OneToOneField(help_text='前台用户', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='前台用户')),
            ],
            options={
                'verbose_name': '前台用户',
                'verbose_name_plural': '前台用户',
                'ordering': ['-join_time'],
            },
        ),
    ]
